/* DULEO Auth — migração gradual para Supabase Auth. */
(()=>{
const URL='https://mmrxwrfydjizichpcagt.supabase.co',KEY='sb_publishable_b4sZCHa72u1TDIMXkiz8rQ_YkLLsbdb';let client=null;
const load=()=>new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
async function start(){try{await load();client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.DULEOAuth=client;wire()}catch(e){console.warn('DULEO Auth:',e.message)}}
function wire(){const form=document.querySelector('#formLogin'),input=document.querySelector('#loginUsuario');if(!form||!input)return;const label=input.closest('label');if(label)label.firstChild.textContent='Usuário ou e-mail';input.placeholder='Usuário ou e-mail';form.addEventListener('submit',async e=>{const login=input.value.trim();if(!login.includes('@'))return;e.preventDefault();const pass=document.querySelector('#loginSenha')?.value||'',msg=document.querySelector('#mensagemLogin');if(msg)msg.textContent='Autenticando online...';const {data,error}=await client.auth.signInWithPassword({email:login,password:pass});if(error){if(msg)msg.textContent='E-mail ou senha inválidos.';return}const meta=data.user.user_metadata||{},nome=meta.nome||login.split('@')[0].toUpperCase(),filial=document.querySelector('#loginFilial')?.value||'todas';localStorage.setItem('duleo_auth_user',JSON.stringify({id:data.user.id,email:data.user.email,nome}));localStorage.setItem('duleo_s3',JSON.stringify({uid:data.user.id,filial}));location.reload()})}
window.DULEOAuthSetup=async(email,password,nome)=>{await start();if(!client)throw new Error('Auth indisponível');const r=await client.auth.signUp({email,password,options:{data:{nome:nome||email.split('@')[0].toUpperCase()}}});if(r.error)throw r.error;return r.data};
window.DULEOAuthSignOut=async()=>{if(client)await client.auth.signOut();localStorage.removeItem('duleo_s3');localStorage.removeItem('duleo_auth_user');location.reload()};start();
})();
