/* DULEO + Supabase — sincronização + carregamento das camadas online */
(()=>{
const SUPABASE_URL='https://mmrxwrfydjizichpcagt.supabase.co',SUPABASE_KEY='sb_publishable_b4sZCHa72u1TDIMXkiz8rQ_YkLLsbdb',STORE_KEYS=['duleo_i3','duleo_f3','duleo_u3','duleo_m3','duleo_a3','duleo_t3'],SESSION_KEY='duleo_s3',TABLE='duleo_store';
const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'};let ready=false,applyingRemote=false,running=false,queued=false,chain=Promise.resolve();const json=v=>{try{return JSON.parse(v)}catch{return null}};
const setLocal=(k,v)=>{applyingRemote=true;if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);applyingRemote=false};
async function get(){const r=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}?select=key,value,updated_at`,{headers,cache:'no-store'});if(!r.ok)throw Error('Supabase '+r.status);return r.json()}
async function put(rows){if(!rows.length)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows)});if(!r.ok)throw Error('Supabase '+r.status)}
async function sync(){if(running){queued=true;return}running=true;try{const rows=await get(),map=new Map(rows.filter(x=>STORE_KEYS.includes(x.key)).map(x=>[x.key,x])),missing=[];for(const k of STORE_KEYS){const row=map.get(k);if(row){const v=JSON.stringify(row.value);if(localStorage.getItem(k)!==v)setLocal(k,v)}else{const v=json(localStorage.getItem(k));if(v!==null)missing.push({key:k,value:v})}}if(missing.length)await put(missing);ready=true;window.DULEOSupabase.ready=true;document.dispatchEvent(new CustomEvent('duleo:supabase-ready'))}catch(e){ready=false;window.DULEOSupabase.ready=false;console.warn('DULEO Supabase:',e.message);document.dispatchEvent(new CustomEvent('duleo:supabase-error',{detail:{message:e.message}}))}finally{running=false;if(queued){queued=false;sync()}}}
const originalSet=localStorage.setItem.bind(localStorage);localStorage.setItem=(k,v)=>{originalSet(k,v);if(STORE_KEYS.includes(k)&&ready&&!applyingRemote){const value=json(v);if(value!==null)chain=chain.then(()=>put([{key:k,value}])).catch(e=>console.warn('DULEO Supabase:',e.message))}};
window.DULEOSupabase={url:SUPABASE_URL,table:TABLE,ready:false,sync,sessionKey:SESSION_KEY};window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>document.visibilityState==='visible'&&sync());
function asset(type,url,attr){if(document.querySelector(`[data-${attr}]`))return;const x=document.createElement(type);x[attr]='1';if(type==='script')x.src=url;else{x.rel='stylesheet';x.href=url}document.head.appendChild(x)}
asset('link','duleo-enhancements.css?v=2.1.0','duleo-enhancements');asset('script','duleo-enhancements.js?v=2.1.0','duleo-enhancements-script');asset('script','duleo-auth.js?v=1.0.0','duleo-auth-script');sync();
})();
